services:
  - docker
language: generic

env:
  - REPO=ci
  - REPO={core,caffe/cpu}/kinetic webtools viz noether noether-webtools a5
  - REPO={core,caffe/cpu}/indigo
  - REPO={ros-core-nvidia,ros-base-nvidia,ros-robot-nvidia,core-nvidia,caffe/gpu}/kinetic
  - REPO={ros-core-nvidia,ros-base-nvidia,ros-robot-nvidia,core-nvidia,caffe/gpu}/indigo
  - REPO={ros-core-nvidia,ros-base-nvidia,ros-robot-nvidia}/lunar

script: ./build.sh $REPO
